### ISSUE TITLE
minecraft

### ISSUE THREAD

**Issue by dario657** [MicrosoftDocs/minecraft-creator#833]
[Hier Feedback eingeben]

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er wird für die Verknüpfung von learn.microsoft.com zum GitHub-Issue benötigt.*

* ID: a8a88ce5-d418-c1bf-0edc-cc1836d68ee4
* Version Independent ID: 50d65cea-41e6-8478-048b-cf192b12503a
* Content: [Installieren von Add-Ons in Minecraft: Bedrock Edition](https://learn.microsoft.com/de-de/minecraft/creator/documents/addonpackinstallation?tabs=Windows10)
* Content Source: [creator/Documents/AddonPackInstallation.md](https://github.com/MicrosoftDocs/minecraft-creator-pr.de-DE/blob/live/creator/Documents/AddonPackInstallation.md)
* Product: **gaming**
* GitHub Login: @v-josjones
* Microsoft Alias: **v-josjones**
```[tasklist]
### Tasks
- [ ] https://github.com/MicrosoftDocs/minecraft-creator/pull/832
- [ ] https://github.com/MicrosoftDocs/minecraft-creator/pull/831
- [ ] https://github.com/MicrosoftDocs/minecraft-creator/pull/830
- [ ] https://github.com/MicrosoftDocs/minecraft-creator/issues/823
- [ ] https://github.com/MicrosoftDocs/minecraft-creator/issues/799
- [ ] https://github.com/MicrosoftDocs/minecraft-creator/issues/827
```

**Comment by dario657** [comment]
hello
